version: '3'

services:
    main-server:
        build:
            context: ./server
        ports: 
            - 2345:2345
        volumes:
            - ./server/src:/app
        container_name: web-server